// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir} from '../models';

export function Decrypt(arg1:string,arg2:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function Encrypt(arg1:string,arg2:string):Promise<string>;

export function GetDirs(arg1:string):Promise<Array<dir.Dir>>;

export function GetUserHome():Promise<string>;

export function MoveFromVault(arg1:string):Promise<void>;

export function MoveToVault(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;
