// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir} from '../models';

export function Decrypt():Promise<void>;

export function Encrypt(arg1:string):Promise<void>;

export function GetDirs(arg1:string):Promise<Array<dir.Dir>>;

export function GetUserHome():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;
