// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt() {
  return window['go']['uifunctions']['UIFunctions']['Decrypt']();
}

export function Encrypt(arg1) {
  return window['go']['uifunctions']['UIFunctions']['Encrypt'](arg1);
}

export function GetDirs(arg1) {
  return window['go']['uifunctions']['UIFunctions']['GetDirs'](arg1);
}

export function GetUserHome() {
  return window['go']['uifunctions']['UIFunctions']['GetUserHome']();
}

export function OpenFile(arg1) {
  return window['go']['uifunctions']['UIFunctions']['OpenFile'](arg1);
}
