// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir} from '../models';

export function GetDirs(arg1:string):Promise<Array<dir.DirList>>;

export function GetUserHome():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;
