// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirs(arg1) {
  return window['go']['main']['App']['GetDirs'](arg1);
}

export function GetUserHome() {
  return window['go']['main']['App']['GetUserHome']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}
