// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDirs(arg1:string):Promise<Array<main.DirList>>;

export function GetUserHome():Promise<string>;
